language: node_js
node_js:
  - "0.10"

after_success:
  - chmod +x ./scripts/*.sh
  - chmod +x ./scripts/for-travis/*.sh
  - ./scripts/for-travis/build-and-deploy.sh

env:
 global:
  - TDDBIN_ROOT_DOMAIN: tddbin.com
  - GH_EMAIL: contact+travis-for-tddbin@uxebu.com
  - GH_REF: github.com/tddbin/katas.git
  - secure: Cl//mlnwVWCkXog9KewWpZmnsRxC89RRYih+jfFNJ+/Alh4I86TBQAr9ZgdVeqMNXKqpl4FvlWcG4he36WxuH9LuWO35RlzbIcAILghOrwNiGofeD7gjZ4I5A4ikau87mHUG0K3+csSOy7cYduFw/mMiaYGpU1T+WSTsqG7p4Sk=