language: node_js
node_js:
  - "0.10"

after_success:
  - chmod +x ./scripts/*.sh
  - chmod +x ./scripts/for-travis/*.sh
  - ./scripts/for-travis/build-and-deploy.sh

env:
 global:
  - TDDBIN_ROOT_DOMAIN: tddbin.com
  - GH_EMAIL: contact+travis-for-tddbin@uxebu.com
  - GH_REF: github.com/tddbin/katas-service.git
  - secure: aKe+sanSie2Gj11Qk+mSr+X9Z/ddXcAYog0NMXCr5I7ZbyqaXj9Uih6ttjD36kmqyOq4IeWoyP7GoMw7iYvuZc+iZlzrnTx0iRqxyx30xUIpBU/SEcyoFj8z/iUk6JNvoqFo6qgzPV+O1GW+0P8XSsUSD+0EI0W5lz4NszMyMic=